#!/usr/bin/env python3

import cgi, json
from timetable import parse_html

def get_file( form, field ):
    try:
        file_it = form[field].file
    except Exception as e:
        return { 'success': 0, 'message': 'No file found.' }

    rawfile = file_it.read(1000000)
    if not rawfile: return { 'success': 0, 'message': 'Empty file uploaded.' }
    if file_it.read(1): return { 'success': 0, 'message': 'File too big.' }

    processed = parse_html( rawfile )
    if not processed: return { 'success': 0, 'message': 'No entries processed.' }

    return { 'success': 1, 'message': 'Thank you for your submission.', 'processed': processed }

msg = get_file( cgi.FieldStorage(), 'timetable' )

print( 'Content-Type: application/json\n\n' )
print( json.dumps( msg ) )
